/**
 * DEPLOYHELP LLC - Main JavaScript Module
 * Generated by Developer Agent
 */

import { initHeader } from './components/header.js';
import { initFooter } from './components/footer.js';
import { initAnimations, initModals } from './utils.js';

class DeployHelpApp {
    constructor() {
        this.components = {};
        this.isInitialized = false;
    }

    init() {
        if (this.isInitialized) return;
        
        // Initialize components
        this.components.header = initHeader();
        this.components.footer = initFooter();
        
        // Initialize utilities
        initAnimations();
        initModals();
        
        // Initialize app-specific features
        this.initFeatures();
        
        this.isInitialized = true;
        console.log('DeployHelp App initialized');
    }

    initFeatures() {
        // Add app-specific initialization here
        this.setupEventListeners();
        this.updateCopyrightYear();
    }

    setupEventListeners() {
        // Smooth scrolling
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener('click', function (e) {
                const href = this.getAttribute('href');
                if (href === '#') return;
                
                e.preventDefault();
                const target = document.querySelector(href);
                if (target) {
                    target.scrollIntoView({
                        behavior: 'smooth',
                        block: 'start'
                    });
                }
            });
        });
    }

    updateCopyrightYear() {
        const yearElements = document.querySelectorAll('[data-year]');
        const currentYear = new Date().getFullYear();
        yearElements.forEach(el => {
            el.textContent = currentYear;
        });
    }
}

// Initialize app when DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => {
        const app = new DeployHelpApp();
        app.init();
    });
} else {
    const app = new DeployHelpApp();
    app.init();
}

export default DeployHelpApp;
