/**
 * Footer Component
 * Generated by Developer Agent
 */

export function initFooter() {
    const updateCopyright = () => {
        const yearElements = document.querySelectorAll('[data-year]');
        const currentYear = new Date().getFullYear();
        yearElements.forEach(el => {
            el.textContent = currentYear;
        });
    };

    updateCopyright();

    return {
        updateCopyright
    };
}
